### ISSUE TITLE
Dependency injection is not working properly

### ISSUE THREAD

**Issue by elias-rod** [betalgo/openai#142]
**Describe the bug**
Dependency injection is not working for Azure Functions with this overload serviceCollection.AddOpenAIService();
It only works with the overload serviceCollection.AddOpenAIService(settings => { settings.ApiKey = "APIKEY" });
It seems that the constructor of the OpenAIService is not called in the expected order and so the OpenAiOptions param has the key empty.

**Your code piece**
https://github.com/elias-rod/ChatGptPoc/tree/di-error
(branch di-error)

My secrets.json is
```
{
  "OpenAiOptions": {
    "ApiKey": "xxx"
  }
}
```

Error repro steps
1. Download repo
2. Checkout to branch branch di-error
3. Create secrets.json
4. Execute program

**Screenshots**
![image](https://user-images.githubusercontent.com/12984787/223118294-ba5cbea1-21b0-4995-8e93-8b755e6b422e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Language c#
 - Version Visual Studio 2022 17.5

**Comment by kayhantolga** [comment]
it seems like your json file option key is incorrect. 
❌ OpenAiOptions
✔️ OpenAIServiceOptions
```
{
  "OpenAIServiceOptions": {
    "ApiKey": "xxx"
  }
}
```
