### ISSUE TITLE
Can not install into my project. 

### ISSUE THREAD

**Issue by ericliu0408** [betalgo/openai#147]
Could you please help to solve it :

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Betalgo.OpenAI.GPT3 6.7.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by Velorexe** [comment]
In [NuGet under 'package manager'](https://www.nuget.org/packages/Betalgo.OpenAI.GPT3/#supportedframeworks-body-tab) for this package, you can see which .NET frameworks are supported. In this case, it's .NET 6.0, so it won't work with .NET version 4.7.2. You'd need to change the target framework for your project to .NET 6.0 to use this package.

**Comment by kayhantolga** [comment]
@ericliu0408 https://github.com/betalgo/openai/pull/141 please follow this branch. We will be adding .net 2.0 support soon

**Comment by ericliu0408** [comment]
> In [NuGet under 'package manager'](https://www.nuget.org/packages/Betalgo.OpenAI.GPT3/#supportedframeworks-body-tab) for this package, you can see which .NET frameworks are supported. In this case, it's .NET 6.0, so it won't work with .NET version 4.7.2. You'd need to change the target framework for your project to .NET 6.0 to use this packagy

My project is a vsto office addin, which could only be set to .net framework 4.8 the highest. I don't know if there is any way to solve it.
