### ISSUE TITLE
Client is not configurable

### ISSUE THREAD

**Issue by elias-rod** [betalgo/openai#151]
**Describe the bug**
The Http client is not exposed and cannot be configured, so a call to audio transcription with Whisper is very limited to small files even though the service supports up to 1 hour of audio, the call is interrupted after the default 100 seconds which is not enough. Small files are processed correctly though.

**Your code piece**
```
var audioCreateTranscriptionResponse = await _iOpenAIService.Audio.CreateTranscription(audioCreateTranscriptionRequest);
```
**Result**
Task is cancelled

**Expected behavior**
To be able to configure the client timeout.

**Comment by kayhantolga** [comment]
I will have a look at this, meanwhile please have a look at this discussion, it may help you.
https://github.com/betalgo/openai/discussions/148#discussioncomment-5255172

**Comment by elias-rod** [comment]
Thank you, for anyone looking a temporary workaround:
Instead of:
`serviceCollection.AddOpenAIService();`
Use this:
```
serviceCollection.AddOptions<OpenAiOptions>();
serviceCollection.AddHttpClient<IOpenAIService, OpenAIService>((httpClient) => httpClient.Timeout = TimeSpan.FromMinutes(30));
serviceCollection.Configure<OpenAiOptions>(hostBuilderContext.Configuration.GetSection(OpenAiOptions.SettingKey));
```
