### ISSUE TITLE
Not able to specify the chat context

### ISSUE THREAD

**Issue by MedjahdiKaram** [betalgo/openai#168]
**Describe the bug**
We are not able to specify the chat context

**Additional context**
The context should be added to be able to use the same chat

**Comment by sannae** [comment]
Hi! First-time contributor here, please be understanding 😅 

Apparently right now the OpenAI API doesn't support the chat historical context, see [this discussion](https://community.openai.com/t/how-do-you-maintain-historical-context-in-repeat-api-calls/34395) for further details. 

The simplest way is to always include the whole conversation history - or a summary of it - in each new request (even [ChatGPT responded this way](https://community.openai.com/t/how-do-you-maintain-historical-context-in-repeat-api-calls/34395/14)😆 ), but I guess it's unsustainable as token consumption would skyrocket.

We'll probably have to wait for the API to offer session management to replicate the experience in [chat.openai.com](https://chat.openai.com/chat).
