### ISSUE TITLE
Answers, Classification, Search Endpoint Deprecation

### ISSUE THREAD

**Issue by LockmanB** [betalgo/openai#17]
**Describe the bug**
Today, we’re announcing that we will be deprecating the Answers, Classifications, and Search endpoints.

Since releasing these endpoints, we’ve developed new methods that achieve better results for these tasks. As a result, we’ll be removing the Answers, Classifications, and Search endpoints from our documentation and removing access to these endpoints on December 3, 2022.

We encourage anyone using these endpoints to switch over to newer techniques which produce better results, and have developed transition guides to help with this process.

**Your code piece**
```
Exception message:
Org org-OqrhlCeqzLz6NBDkPuE1o5IY does not have access to the answers endpoint, likely because it is deprecated. Please see https://community.openai.com/t/answers-classification-search-endpoint-deprecation/18532 for more information and reach out to deprecation@openai.com if you have any questions.
```
**Result**
If you are currently using these endpoints, this change will not immediately impact you. Prior to December 3, you will still be able to make requests and access the endpoint documentation by directly navigating to these pages:

**Additional context**
[Link to the official message.](https://community.openai.com/t/answers-classification-search-endpoint-deprecation/18532)

**Comment by kayhantolga** [comment]
Thanks for the Issue. Removed deprecated endpoints at v6.2.0 .
