### ISSUE TITLE
Support proxy server configuration

### ISSUE THREAD

**Issue by git102347501** [betalgo/openai#175]
**Is your feature request related to a problem? Please describe.**
I have encountered a very important issue. My environment does not have direct access to apiopenapi.com, and I need an agent fu

**Describe the solution you'd like**
Support configuring proxy servers in options to achieve the effect of proxy request APIs
```
builder.Services.AddOpenAIService(settings => {
    settings.ProxyUrl = "proxy serve url";
    settings.ProxyPort = "proxy serve port";
});
```

**Comment by kayhantolga** [comment]
have you tried setting BaseUrl to your ProxyUrl?

https://github.com/betalgo/openai/blob/2869bdbfb5feb625d9d483f2f34571ac27da3594/OpenAI.SDK/OpenAiOptions.cs#L79

**Comment by JohnnyZhang0628** [comment]
@git102347501 @kayhantolga I try to use new HttpClient add proxy .It's Ok.This is my code.
```
var handler = new HttpClientHandler()
{
    Proxy = new WebProxy("http://127.0.0.1:10809"),
    UseProxy = true
};

var client = new HttpClient(handler);

var openAiService = new OpenAIService(new OpenAiOptions()
{
    ApiKey = "",
}, client);
```

**Comment by sammadox** [comment]
As long as the API key is valid and the proxy server is configured correctly, this code should work as intended.

**Comment by GrowingHacker** [comment]
> @git102347501 @kayhantolga我尝试使用新的 HttpClient 添加代理。没关系。这是我的代码。
> 
> ```
> var handler = new HttpClientHandler()
> {
>     Proxy = new WebProxy("http://127.0.0.1:10809"),
>     UseProxy = true
> };
> 
> var client = new HttpClient(handler);
> 
> var openAiService = new OpenAIService(new OpenAiOptions()
> {
>     ApiKey = "",
> }, client);
> ```

However, how to use vless+ws+tls proxy, this is a problem
