### ISSUE TITLE
openAIService.Audio.CreateTranscription Returns completionResult.Successful even on invalid_request_error

### ISSUE THREAD

**Issue by dannyr-git** [betalgo/openai#179]
**Describe the bug**
Send a CreateTranscription with a faulty key

**Your code piece**
```
          var completionResult = await _openAIService.Audio.CreateTranscription(new AudioCreateTranscriptionRequest
            {
                Model = Models.WhisperV1,
                ResponseFormat = StaticValues.AudioStatics.ResponseFormat.Text,
                File = fileBytes,
                FileName = inmp3.Name,
            });

```
**Result**
completionResult.Successful = true
completionResult.Text = 
{
    "error": {
        "message": "Incorrect API key provided: sk-QoVWP***************************************m111. You can find your API key at https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": "invalid_api_key"
    }
}

**Expected behavior**
completionResult.Successful should be false

**Screenshots**
![image](https://user-images.githubusercontent.com/15082948/225967097-e56caef6-b915-4e37-91b4-8eecc50e1e14.png)

**Desktop (please complete the following information):**
 - Windows
 - C#
 - 6.8.0

**Comment by kayhantolga** [comment]
thanks for report, I will have a look

**Comment by kayhantolga** [comment]
Interesting! I tried to reproduce your example by updating my OpenAI key with an invalid one, and as you can see in the screenshot, it worked as expected. 🤔 

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/1096362/226191571-1b6937f1-9b08-45da-91af-7b4eabc086f6.png">
