### ISSUE TITLE
Question: get started with AzureOpenAI

### ISSUE THREAD

**Issue by WeihanLi** [betalgo/openai#181]
Great thanks for the project, I'm trying to use it with Azure OpenAI service, but do not know how to find the DeploymentId, could you please help, thanks

**Comment by WeihanLi** [comment]
I'm using the following code for the AzureOpenAI

```c#
var options = new OpenAiOptions()
{
	BaseDomain = " https://spark.openai.azure.com",
	ApiKey = apiKey,
	DeploymentId = "gpt35",
	ResourceName = "spark",
	ProviderType = ProviderType.Azure,
};
var openAiService = new OpenAIService(options);
var completionResult = await openAiService.ChatCompletion.CreateCompletion(new ChatCompletionCreateRequest
{
	Messages = new List<ChatMessage>
	{
		ChatMessage.FromSystem("You are a helpful assistant."),
		ChatMessage.FromUser("What's new in .NET 6")
	},
	Model = Models.ChatGpt3_5Turbo // "gpt-35-turbo" also not working
});
```

`completionResult` has error as follows:

```
{"Code":"404","Message":"Resource not found"}
```

While I could call the AzureOpenAI API by following the rest api docs, after some research, I found that the API is not the same, wondering that maybe there's something wrong with my way calling AzureOpenAI.

For details, the raw Azure OpenAI request likes below:

```
POST https://spark.openai.azure.com/openai/deployments/gpt35/completions?api-version=2022-12-01
Host: spark.openai.azure.com
Content-Type: application/json
api-key: <api-key>

{
  "prompt": "<|im_start|>system\nThe system is a helpful AI assistant.\n<|im_end|>\n<|im_start|>user\nWhat's new with .NET 6?\n<|im_end|>\n<|im_start|>assistant",
  "max_tokens": 800,
  "temperature": 1,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "top_p": 0.95,
  "stop": ["<|im_end|>"]
}
```

The request fired with before code like follows:

```
POST https://spark.openai.azure.com/openai/deployments/gpt35/chat/completions?api-version=2022-12-01 HTTP/1.1
Host: spark.openai.azure.com
api-key: <api-key>
Content-Type: application/json; charset=utf-8

{"messages":[{"role":"system","content":"You are a helpful assistant."},{"role":"user","content":"What\u0027s new in .NET 6"}],"model":"gpt-3.5-turbo"}
```

**Comment by kayhantolga** [comment]
I recently got access to Azure OpenAI. I couldn't find a chance to try services before releasing the SDK. I will check this issue as soon as possible. 
I have used this documentation as a reference, it may help you too.
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference

**Comment by cgtholdingsllc1** [comment]
I am tracking this also as I started using this library today with Azure OpenAI service and have yet to get it working.

**Comment by cgtholdingsllc1** [comment]
I did some quick test code with Azure OpenAI and this worked.
`
CompletionMessage completionMessage = new( message );
                HttpRequestMessage request = new()
                {
                    Method = HttpMethod.Post,
                    RequestUri = new Uri( $"https://{resourceName}.openai.azure.com/openai/deployments/{deploymentName}/completions?api-version=2022-12-01" ),
                    Content = new StringContent( completionMessage.ToString(), Encoding.UTF8, "application/json" ),
                };
                request.Headers.Clear();
                request.Headers.Accept.Add( new MediaTypeWithQualityHeaderValue( "application/json" ) );
                request.Headers.Add( "api-key", apiKey );

                var response = await _httpClient.SendAsync( request );
`
Not saying this is the code you should use but giving guidance on what normally works with httpclient.
The completionMessage is a quick class I created mimicking the following JSON.
{
  "prompt": "",
  "temperature": 0.7,
  "top_p": 0.95,
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "max_tokens": 800,
  "stop": [
    "<|im_end|>"
  ]
}

**Comment by doggy8088** [comment]
@kayhantolga May I ask which `Betalgo.OpenAI.GPT3` version can I use for AOAI?

Also, I think the `ResourceName` property is not necessary for `OpenAiOptions` in AOAI.

**Comment by remixtedi** [comment]
If the client is configured to use Azure OpenAI service then Image generation doesn't work because it is not available on Azure, is there a way to have the client configured for both platforms? to use Azure for chat completions and OpenAI Dalle for images?
