### ISSUE TITLE
Question/Bug: Does anyone else get HTTP request time about on ca 50% of requests?

### ISSUE THREAD

**Issue by asieradzk** [betalgo/openai#186]
When calling create completion I get timeout about 50% of the time.

Also no obvious way to change this so every time I am just sitting here waiting for 100 seconds.

**Comment by kayhantolga** [comment]
I think your issues are related to OpenAI API rather than the library. This is just a wrapper library for OpenAI. 
You can raise API-related questions in the community forum or their Discord channel
https://community.openai.com/
