### ISSUE TITLE
Dalle Image Request Issue

### ISSUE THREAD

**Issue by cikdibest** [betalgo/openai#197]
When i try the below code :

            var imageResult = await openAiService.Image.CreateImage(new ImageCreateRequest
            {
                Prompt = "Laser cat eyes",
                N = 2,
                Size = StaticValues.ImageStatics.Size.Size256,
                ResponseFormat = StaticValues.ImageStatics.ResponseFormat.Url,
                User = "TEST"
            });
            
            i get error for image response like : 
            
            unhandled error: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.

It should be able to get Image Result

**Comment by kayhantolga** [comment]
is there any chance you can capture requests and responses and share them with me? It seems like API doesn't return JSON response.
