### ISSUE TITLE
The response ended prematurely.

### ISSUE THREAD

**Issue by tianqingshuilan** [betalgo/openai#209]
**Describe the bug**
When accessing the web front-end and chatting with ChatGPT, there will be occasional interruptions during the chat process. Check the log and find that the error is: `System.IO.IOException: The response ended prematurely.`

**Your code piece**
```CSharp
// in My Service
await foreach (var completion in completionResult)
{
    if (completion.Successful)
    {
        string res = completion.Choices.First().Message.Content;
        jm.code = 0;
        jm.data = res;
        jm.msg = "OK";
        yield return jm;
        sb.Append(res);
    }
    else
    {
        jm.code = -1;
        if (completion.Error == null)
        {
            throw new Exception("Unknown Error");
        }

        sb.AppendLine();
        jm.msg = $"{completion.Error.Code}: {completion.Error.Message}";
        _cache.Remove($"{_user.ID}-ing");

        noErr = false;
        yield return jm;
    }
}
```

```CSharp
// in MyControllerAction
await foreach (var item in _apiServices.ChatYield(userMessage, sysMessage))
{
    byte[] msgBytes = Encoding.UTF8.GetBytes($"data: {JsonConvert.SerializeObject(new { code = item.code, data = item.data, msg = item.msg })}\r\r");
    await Response.Body.WriteAsync(msgBytes, 0, msgBytes.Length);
    await Response.Body.FlushAsync();

    if (item.code != 0)
    {
        NLogUtil.WriteAll(NLog.LogLevel.Error, LogType.ApiRequest, "Chat Err", item.msg);
    }
}
```
**Result**
The stack information location of exception handling is in the Service `await foreach` line of code.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: docker-debian
 - Language [c#]
 - Version [6.8.3]

**Additional context**
None.

**Comment by kayhantolga** [comment]
This issue may be related to https://github.com/betalgo/openai/pull/243 or https://github.com/betalgo/openai/discussions/254. Please take a look at both of these. If they don't solve your issue, please reopen the issue.
