### ISSUE TITLE
Whisper API: AudioCreateTranscriptionResponse.Text contains error

### ISSUE THREAD

**Issue by Swimburger** [betalgo/openai#221]
**Describe the bug**
When the Whisper API returns an error
- the `AudioCreateTranscriptionResponse.Successful` is `true` 
- the `AudioCreateTranscriptionResponse.Error` object is null
- the `AudioCreateTranscriptionResponse.Text` property contains the error JSON

**Expected behavior**
When the Whisper API returns an error
- the `AudioCreateTranscriptionResponse.Successful` should be `false` 
- the `AudioCreateTranscriptionResponse.Error` object should contain the error object
- the `AudioCreateTranscriptionResponse.Text` property should be null

**Desktop (please complete the following information):**
 - Version 6.8.3

**Comment by Swimburger** [comment]
Looks like it's also an issue for the successful case, the `AudioCreateTranscriptionResponse.Text` contains JSON instead of the text itself:
```csharp
Console.Writeline(response.Text); // {"text":"test"}
```

**Comment by kayhantolga** [comment]
Could you share a sample? My test case works fine on error cases.

**Comment by Swimburger** [comment]
I believe it's because your test cases set the `AudioCreateTranscriptionRequest.AudioCreateTranscriptionRequest` property.
In my code I didn't set that property and I didn't realize that was causing the issue until I dug into it deeper for the PR.
I don't have a straightforward PR, but you can remove this line from your sample to test it out.
https://github.com/betalgo/openai/blob/master/OpenAI.Playground/TestHelpers/AudioTestHelper.cs#L26

**Comment by kayhantolga** [comment]
Does it mean 👇🏻this is not a case anymore?

> When the Whisper API returns an error
> 
> the AudioCreateTranscriptionResponse.Successful is true
> the AudioCreateTranscriptionResponse.Error object is null
> the AudioCreateTranscriptionResponse.Text property contains the error JSON

**Comment by Swimburger** [comment]
This was also the case because the `ResponseFormat` wasn't set, so instead of serializing the JSON, it'd put all the JSON into the `Text` property. It should be all solved by that PR.

**Comment by kayhantolga** [comment]
Cool, I will be releasing a new version soon. Thanks for all your contributions.

**Comment by kayhantolga** [comment]
solved
https://github.com/betalgo/openai/releases/tag/v6.8.5
