### ISSUE TITLE
Reference to SAM project in Wiki is broke or not found

### ISSUE THREAD

**Issue by fitprotracker** [betalgo/openai#257]
**Describe the bug**

**Your code piece**
```
throw new Exception("");
```
**Result**
More detail about what happened when you run your code.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Language [e.g. c#]
 - Version [e.g. 0.0.3]

**Additional context**

**Comment by kayhantolga** [comment]
removed temporarily and asked for an update from the repo owner. thanks for reporting.
