### ISSUE TITLE
Invalid exception is thrown when server is unavailable

### ISSUE THREAD

**Issue by miroljub1995** [betalgo/openai#277]
**Describe the bug**
If server is currently unavailable (503 status), we receive some weird exception `<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.`
Looks like it is missing `response.EnsureSuccessStatusCode()` before this line:
https://github.com/betalgo/openai/blob/0513b27e888670255240b7cade217b542bdddd85/OpenAI.SDK/Extensions/HttpclientExtensions.cs#L16
**Result**
Error: `<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.`

**Expected behavior**
Let dotnet throw `HttpRequestException` so we can implement retry logic.

**Desktop:**
 - OS: Ubuntu
 - Language: c#
 - Dotnet version: 7
 - Lib version: 6.8.4

**Comment by winzig** [comment]
Wonder if you're seeing the same basic issue as I am: https://github.com/betalgo/openai/issues/266

**Comment by miroljub1995** [comment]
Yeah, it can be if status is not 2xx.

**Comment by Artein** [comment]
I started to receive such exceptions too. Initially thought it is something with my requests, cause I am expecting a response in JSON format. But eventually found this thread. As a workaround, I can catch that exception and retry my request. 

Is any work planned on that?

**Comment by kayhantolga** [comment]
Using response.EnsureSuccessStatusCode() is causing additional trouble. I am planning to implement specific logic for handling 503 cases.
