### ISSUE TITLE
Install-Package Betalgo.OpenAI

### ISSUE THREAD

**Issue by Barrimoni1990** [betalgo/openai#278]
**Describe the bug**

**Your code piece**
```
throw new Exception("");
```
**Result**
More detail about what happened when you run your code.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Language [e.g. c#]
 - Version [e.g. 0.0.3]

**Additional context**

**Comment by Barrimoni1990** [comment]
Install-Package Betalgo.OpenAI

**Comment by Barrimoni1990** [comment]
Install-Package Betalgo.OpenAI

**Comment by Barrimoni1990** [comment]
Install-Package Betalgo.OpenAI
/
```python

```

**Comment by kayhantolga** [comment]
?
