### ISSUE TITLE
gpt-3.5-turbo-16k

### ISSUE THREAD

**Issue by joephalex** [betalgo/openai#290]
Can you please include as well gpt-3.5-turbo-16k model for the ChatCompletion and also function-calling?

**Comment by jgriffith3433** [comment]
Turbo 0613 has features allowing JSON responses and function calling. No longer having to strong-arm the model into giving you js style responses.

**Comment by oferavnery** [comment]
I Updated the Model to gpt-3.5-turbo-16k and it works fine. Looking forward to having functions support! I wonder how would streaming work if at all for when a function call response is returned. Great Library BTW - Thank you!

**Comment by matteocontrini** [comment]
@oferavnery with streaming the pieces of the JSON are streamed as if they were normal text:

```json
{
    "id": "chatcmpl-7RbxtzQqEv5coBpV1C6UKygmXaECp",
    "object": "chat.completion.chunk",
    "created": 1686815149,
    "model": "gpt-3.5-turbo-0613",
    "choices": [
        {
            "index": 0,
            "delta": {
                "role": "assistant",
                "content": null,
                "function_call": {
                    "name": "function_name",
                    "arguments": ""
                }
            },
            "finish_reason": null
        }
    ]
}
{
    "id": "chatcmpl-7RbxtzQqEv5coBpV1C6UKygmXaECp",
    "object": "chat.completion.chunk",
    "created": 1686815149,
    "model": "gpt-3.5-turbo-0613",
    "choices": [
        {
            "index": 0,
            "delta": {
                "function_call": {
                    "arguments": "{\n"
                }
            },
            "finish_reason": null
        }
    ]
}
```

And so on.

**Comment by kayhantolga** [comment]
Please check the latest beta version at https://www.nuget.org/packages/Betalgo.OpenAI/7.1.0-beta. Additionally, there is a discussion thread about the latest developments at https://github.com/betalgo/openai/discussions/296 that you may find useful.

**Comment by dmki** [comment]
> in the meantime I'm pretty sure just setting the model to a string directly should work:
> 
> Model = "gpt-3.5-turbo-16k",

No, doesn't work. It still says "context length exceeding", even if you send 9K characters.
