### ISSUE TITLE
PerformTextEmbedding is not consistently using paths

### ISSUE THREAD

**Issue by Tiggerito** [betalgo/openai#293]
https://github.com/betalgo/openai/blob/1d9ca2117ada7bde49c38c7a19faad61237ac63a/OpenAI.Utilities/EmbeddingTools.cs#L315C2-L331

```    
public async Task<DataFrame> PerformTextEmbedding(IEnumerable<TextEmbeddingData> textEmbeddingData, string outputFilePath)
    {
        await WriteToTempCsv(textEmbeddingData, outputFilePath);

        var df = ReadAndSplitData(outputFilePath);
        var dfTextList = new List<string>();
        for (var i = 0; i < df.Rows.Count; i++)
        {
            dfTextList.Add(df[EmbedStaticValues.Text][i].ToString() ?? string.Empty);
        }

        var embeddingResults = await GetEmbeddings(dfTextList);
        var newDf = AddEmbeddingsToDf(df, embeddingResults);
        SaveDfToCsv(newDf, outputFilePath);
        ClearTempCsv(outputFilePath);
        return newDf;
    }
```

The use of paths seems a bit confused. The WriteToTempCsv() writes the file into a temp folder, then the ReadAndSplitData tries to read it from the original path. I fixed it with the following changes.

Have WriteToTempCsv return the path where it wrote the file:

```
 public async Task<string> WriteToTempCsv(IEnumerable<TextEmbeddingData> textEmbeddingData, string outputFilePath)
    {
        var tempFilePath = Path.Combine(Path.GetTempPath(), outputFilePath);
        Directory.CreateDirectory(Path.GetDirectoryName(tempFilePath) ?? string.Empty);
        await using var writer = new StreamWriter(tempFilePath);
        await using var csv = new CsvWriter(writer, CultureInfo.InvariantCulture);
        await csv.WriteRecordsAsync((IEnumerable)textEmbeddingData);
        await csv.DisposeAsync();

        return tempFilePath;
    }
```

And then use that returned path for the other actions. I also changed the temp file name, but that may not need to be done:

```
public async Task<DataFrame> PerformTextEmbedding(IEnumerable<TextEmbeddingData> textEmbeddingData, string outputFilePath)
    {
        var tempFilePath = await WriteToTempCsv(textEmbeddingData, $"OpenAI/TextEmbeddingData{DateTime.Now.Ticks}.csv"); // CHANGED

        var df = ReadAndSplitData(tempFilePath); // CHANGED
        var dfTextList = new List<string>();
        for (var i = 0; i < df.Rows.Count; i++)
        {
            dfTextList.Add(df[EmbedStaticValues.Text][i].ToString() ?? string.Empty);
        }

        var embeddingResults = await GetEmbeddings(dfTextList);
        var newDf = AddEmbeddingsToDf(df, embeddingResults);
        SaveDfToCsv(newDf, outputFilePath);
        File.Delete(tempFilePath); // CHANGED
        return newDf;
    }
```

After that, I could create and save, then use the embeddings :-)

Is there any way to pass information in the embeddings about where the text came from? I plan to scrape my documentation website and use ChatGPT to provide answers from it, with links to the source.

Thanks

**Comment by Tiggerito** [comment]
No worries, once that was fixed, I could do what I wanted. I also added a URL property, propagated it to the context and managed to write a prompt to get ChatGPT to reference the URL 😎. Thanks for building this.

**Comment by kayhantolga** [comment]
fixed in latest version

**Comment by govert** [comment]
I ran into this same issue today. Now, checking the 'master' branch after the merges for 7.1.5 I can't see any change to the problematic method here https://github.com/betalgo/openai/blob/c1e88f1b329d69a244d578a09b48b665505961cf/OpenAI.Utilities/Embedding/EmbeddingTools.cs#L315

Am I missing perhaps something?
