### ISSUE TITLE
Increase support for function calls

### ISSUE THREAD

**Issue by sd797994** [betalgo/openai#295]
As indicated in the title

**Comment by kayhantolga** [comment]
@Tekaichi, sorry I just saw your message. I will read and check your comments on the discussion. In the meantime, please review my latest message in the discussion and let me know if you have any feedback on the current implementation.

**Comment by kayhantolga** [comment]
https://www.nuget.org/packages/Betalgo.OpenAI/7.1.0-beta beta version is ready
