### ISSUE TITLE
Function calling example 

### ISSUE THREAD

**Issue by joephalex** [betalgo/openai#315]
Would you please share with me an example  for function calling please to have a clear picture on how it's being used for the beta version

**Comment by kayhantolga** [comment]
Currently only available in playground. I will update Wikipage after releasing the Beta

https://github.com/betalgo/openai/blob/feature/functionCall/OpenAI.Playground/TestHelpers/ChatCompletionTestHelper.cs

**Comment by joephalex** [comment]
Thank you very much. May I know please when the beta will be released?

**Comment by kayhantolga** [comment]
https://github.com/betalgo/openai/wiki/Function-Calling
