### ISSUE TITLE
Support for Azure OpenAI DALLE

### ISSUE THREAD

**Issue by remixtedi** [betalgo/openai#318]
I got access to DALLE on my Azure and tried to use the same client I'm using for chat completions but it returns a 404 Resource Not Found error. 
It looks like the endpoint is different from the original OpenAI endpoint and it is like this: 
`https://YOUR-RESOURCE-NAME.openai.azure.com/openai/images/generations:submit?api-version=2023-06-01-preview`

This is a sample code that I got from Azure Playground for DALLE
```python
#Note: The openai-python library support for Azure OpenAI is in preview.
import os
import openai
openai.api_type = "azure"
openai.api_base = "https://YOUR-RESOURCE-NAME.openai.azure.com/"
openai.api_version = "2023-06-01-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")

response = openai.Image.create(
    prompt='USER_PROMPT_GOES_HERE',
    size='1024x1024',
    n=1
)

image_url = response["data"][0]["url"]
``` 

I guess this is not supported yet and would be happy if you will change the implementation for image generations if the provider type is Azure.

**Comment by kayhantolga** [comment]
Hi, I don't think this is supported in this repository yet. If you would like to create a pull request related to this, I would be happy to merge it.
