### ISSUE TITLE
CreateCompletionAsStream blocking

### ISSUE THREAD

**Issue by metalisai** [betalgo/openai#331]
I've run into an issue where in CreateCompletionAsStream methods reader.EndOfStream can block the executing thread until the entire request completes. I believe this is due to EndOfStream needing to wait for data from the underlying stream to determine if there is another line or EOS. This can lead to unresponsiveness in some applications.

https://github.com/betalgo/openai/blob/012af713fd880cfef17e42603289222f7075371f/OpenAI.SDK/Managers/OpenAIChatCompletions.cs#L36-L38

In my application, I've patched it as follows, and it seems to resolve the issue. I believe ReadLineAsync with CancellationToken was added in .NET 7.

**.NET 7 fix**
```
string line;
while ((line = await reader.ReadLineAsync(cancellationToken)) != null)
{
    // loop
}

**Comment by KFeiHe** [comment]
I also encountered the same problem. I am developing a program using Winappsdk, and the interface may get stuck when using streaming

**Comment by kayhantolga** [comment]
Is there any sample project I can test this bug?

**Comment by metalisai** [comment]
I don't have one that I could share, but any single threaded SynchronizationContext should be blocked, like Blazor server app or calling the mentioned method from an UI thread. Code triggered from elsewhere, like timers etc are blocked. Here is the difference it made it my Blazor app:

https://github.com/betalgo/openai/assets/13243133/1d9f8808-df5f-4db0-95a1-33857f185c10

**Comment by Almis90** [comment]
I had similar issue with MAUI on Windows, my solution was to run it on different thread using Task.Run. You might also need to run the UI update on UI thread unless you are using Binding (MVVM).

**Comment by ogix** [comment]
I have the same issue with Blazor. Please fix.
