### ISSUE TITLE
Allow providing function parameters schema as a string

### ISSUE THREAD

**Issue by admg** [betalgo/openai#333]
Now you can only provide strictly defined object, but this object is not compatible with JSON schema. For example in JSON Schema you can have multiple types for property (array of types) and in FunctionParameters class "Type" is a string. Same problem with array as a root object. 
I use JSchemaGenerator to generate JSON schema from expected result object and it generates schema that cannot be used in this lib.

**Comment by kayhantolga** [comment]
https://github.com/betalgo/openai/issues/333
I have added the FunctionsAsObject type in the new version. This means that you can use your own function builder. Please review the code and let me know if this would be suitable for your solution as well.
