### ISSUE TITLE
Request for Adding Custom API Address in SDK

### ISSUE THREAD

**Issue by phoben** [betalgo/openai#340]
Description: As a developer from China, I would like to provide feedback regarding the usage of OPENAI API. Due to certain restrictions, the official OPENAI API is not accessible in China. However, we have access to alternative mirror interfaces provided by third-party developers. Therefore, I would like to request the addition of a feature in the SDK that allows us to define the API address. This would enable us to not only use the official OPENAI API but also explore and utilize alternative third-party API options. Thank you for your consideration.

**Comment by kayhantolga** [comment]
Why not use [Proxy](https://github.com/betalgo/openai/wiki/Proxy) feature?

**Comment by AWAS666** [comment]
Also works fine using this:
`var openAiService = new OpenAIService(new OpenAiOptions() { BaseDomain = @"http://10.0.0.201:5001/", ApiKey = "test" });`

Just needs something as an api key.
