### ISSUE TITLE
Set content-length in header

### ISSUE THREAD

**Issue by AWAS666** [betalgo/openai#347]
**Is your feature request related to a problem? Please describe.**
It would be nice if this could work with:
[text-generation-webui/openai](https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/README.md)

**Describe the solution you'd like**
By setting a dummy api key and another base domain this can already target apis aside from openai.
The only thing breaking it right now is the fact that oogabooga expects a "content-length" in the header before parsing the json.
[see here](https://github.com/oobabooga/text-generation-webui/blob/ed57a79c6e44c1eafd4667ebd19e72a2143b7a4d/extensions/openai/script.py#L142C8-L142C8)

**Describe alternatives you've considered**
Their implemented http server needs the content length to know the buffer size, so it's likely easier to implement here and as other libraries already work with it they seem to be setting the content length.

**Additional context**
Your implementation overall is pretty good <3

**Comment by kayhantolga** [comment]
https://github.com/betalgo/openai/pull/348#issuecomment-1666941291
