### ISSUE TITLE
JsonException

### ISSUE THREAD

**Issue by LarsLiden** [betalgo/openai#35]
**Describe the bug**
I started getting a JsonException when calling CreateCompletion as of this morning with no change of code on my end.  Wonder if OpenAI changed something?

**Your code piece**
```
 try {
                await GPTSemaphore.WaitAsync();
                CompletionCreateResponse result = await api.Completions.CreateCompletion(completionRequest, "text-davinci-002");
                if (result.Successful) {
                    var resultStrings = result.Choices.Select(c => c.Text).ToList();
                    foreach (var resultString in resultStrings) {
                        prompt.responses.Add(Util.CleanListString(resultString));

                        if (RuntimeConfig.settings.displayOptions.showResults) {
                            Util.WriteLineToConsole("---- RESULT ----", ConsoleColor.DarkCyan);
                            Util.WriteLineToConsole(resultString, ConsoleColor.Cyan);
                        }
                    }
                    GPTRequestsTotal++;
                    return resultStrings.Count;
                } else {
                    // TODO: Handle failures in a smarter way
                    if (result.Error is not null) {
                        Console.WriteLine($"{result.Error.Code}: OpenAI = {result.Error.Message}");
                    }
                }
                throw new Exception("API Failure");
            }
```
**Result**
Exception has occurred: CLR/System.Text.Json.JsonException
An unhandled exception of type 'System.Text.Json.JsonException' occurred in System.Private.CoreLib.dll: ''<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.Text.Json.JsonReaderException : '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

**Expected behavior**
Get a result back

**Screenshots**
![image](https://user-images.githubusercontent.com/6528486/202533922-23fe7688-bcdc-4b4f-b56a-96d77f5f23b8.png)

**Desktop (please complete the following information):**
Windows, C#, 6.5.0 (and 6.4.0)

**Comment by kayhantolga** [comment]
Hi Lars,

I just ran the playground completion test with my account, I could get a successful result. 

It might be related to your account or OpenAI was down for a short time. 
I think API returned an HTML error instead of JSON. 

Do you use any proxy tools, that may trigger the issue? 

Finally, if you can capture the OpenAI response, I can help further.
(I use Laser Cat Eyes to catch network data, if you need help with that I can happily help you.)

**Comment by LarsLiden** [comment]
Yeah, that sounds like it might be the issue (HTML error instead of JSON).   I have a console app so not quite sure how to use that with LaserCatEyes)

**Comment by LarsLiden** [comment]
Just started working again, so may have been outage of some sort with OpenAI.  Closing
