### ISSUE TITLE
Support for Azure OpenAI on your data

### ISSUE THREAD

**Issue by rresua** [betalgo/openai#357]
I got access to Azure Open AI Chat Completions and tried to use "Azure OpenAI on your data" which enables you to run supported chat models such as GPT-35-Turbo and GPT-4 on your data without needing to train or fine-tune models.

- The main [documentation](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/use-your-data)
- The [quickstart guide](https://learn.microsoft.com/en-us/azure/ai-services/openai/use-your-data-quickstart?pivots=rest-api&tabs=command-line)

I guess this is not implemented yet, but I would be very grateful if you keep it in mind for future versions.

**Comment by kayhantolga** [comment]
To be decided later
