### ISSUE TITLE
Change Fine-Tunes Endpoint to new /v1/fine_tuning/jobs endpoint.

### ISSUE THREAD

**Issue by ggrote** [betalgo/openai#366]
As stated in openai blog:

These models can be fine-tuned with our new API endpoint /v1/fine_tuning/jobs. This new endpoint offers pagination and more extensibility to support the future evolution of the fine-tuning API. Transitioning from /v1/fine-tunes to the updated endpoint is straightforward and more details can be found in our new [fine-tuning guide](https://platform.openai.com/docs/guides/fine-tuning). This deprecates the old /v1/fine-tunes endpoint, which will be turned off on January 4th, 2024.

https://openai.com/blog/gpt-3-5-turbo-fine-tuning-and-api-updates

Finetuning gpt-3.5 is not possible with the old endpoint.

**Comment by aghimir3** [comment]
I have submitted a PR for this: #368

**Comment by kayhantolga** [comment]
I am currently working on a code review, and it looks good so far. We will probably release it soon.

**Comment by aglasencnik** [comment]
When will this be out, so we can update the nuget package?
Will this also include the all the advanced features in this endpoint..
E.g. Getting more data from retrieving the fine-tuning job?

**Comment by bmullaly14** [comment]
Stopping by to see if there are any updates on a release date for this patch!
Thanks a bunch.

**Comment by kayhantolga** [comment]
Expecting to release this week, please keep an eye on https://github.com/betalgo/openai/pull/382

**Comment by kayhantolga** [comment]
v7.2.0 released
