### ISSUE TITLE
Hi,I have a question about this

### ISSUE THREAD

**Issue by kon1254** [betalgo/openai#38]
![image](https://user-images.githubusercontent.com/120161470/207018297-3d916cad-13b1-40a9-b1ee-1c91295e77b5.png)
Could you please tell me how to solve it? thank you so much

**Comment by schnerd** [comment]
@kon1254 Your API key has been rotated to protect your account, you can view your new API key here: https://beta.openai.com/account/api-keys. As @kayhantolga mentioned, please do not sure your API key publicly.
