### ISSUE TITLE
Long Responses are truncated

### ISSUE THREAD

**Issue by JohnGalt1717** [betalgo/openai#390]
**Describe the bug**
In the case of a long response (i.e. GPT4 > 3900 characters) from Azure OpenAI the Choice.Content is truncated.  If you put Fiddler in front of it, you can see the whole thing is returned.

**Your code piece**
Just inspecting the Choices.First().Content (there are no other choices)

**Result**
The Content looks to be intentionally truncated with ... on the end of it instead of being the full result.

**Expected behavior**
It should return the entire response just like the Azure OpenAI Studio Playground does for the same request.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Language: C# 8 RC2
 - Version Latest

**Additional context**
Microsoft's beta API also does this.  Not sure if it's a problem with their API server returning something bogus, but the value is there (in that case you can get the BinaryData from the RawResponse in vs code and it will return the whole thing, but if you do ToString or access it any other way it is cut off oddly)

**Comment by kayhantolga** [comment]
Could you please provide a sample prompt? I am unable to find a question that would require the model to generate a response longer than 3900 tokens.

**Comment by shahshyam** [comment]
You need to increase number of max token, something like 1000 and it will work.

**Comment by kayhantolga** [comment]
Closing as not reproducible.
