### ISSUE TITLE
Support for Extensions, eg. Azure CognitiveSearch

### ISSUE THREAD

**Issue by capesean** [betalgo/openai#394]
Can/will this library be able to support extensions, such as the Cognitive Search extension ( [AzureChatExtensionsOptions](https://github.com/Azure/azure-sdk-for-net/blob/76d0ba52f2198a04bd74481a479d33c215f23e79/sdk/openai/Azure.AI.OpenAI/src/Custom/AzureChatExtensionsOptions.cs#L15) ) from Azure?

**Comment by capesean** [comment]
Not possible as of now, as far as I'm aware. You would have to use the Azure SDK.

**Comment by kayhantolga** [comment]
sorry for the question mark 😅, I meant It is possible, I just need the rest API documentation to add support

**Comment by kayhantolga** [comment]
This will be decided later.
