### ISSUE TITLE
I am encountering a 400 error when performing fine-tuning.

### ISSUE THREAD

**Issue by Lenloo** [betalgo/openai#397]
Why am I getting a 400 error when creating fine-tuning? It happens whether I use CreateFineTuningJob or CreateFineTune. Other functionalities like chatting and file uploads work fine through the SDK. I am connecting to the API using a proxy.

**Comment by kayhantolga** [comment]
I bit more context would be great.

**Comment by Lenloo** [comment]
After expanding the detailed error message, it was discovered that the reason might be that when fine-tuning with gpt-3.5-turbo, it requires upgrading my account to a paid plan. Currently, I am using a default account with a $5 pricing tier.
