### ISSUE TITLE
Betalgo package not available in Visual Studio 2022

### ISSUE THREAD

**Issue by LlewellynJones** [betalgo/openai#41]
Installed the Betalgo package in the package manager console and it installed no problem. I just can't reference the package with a using statement.

![Screenshot 2022-12-23 130717](https://user-images.githubusercontent.com/10248399/209405610-17d53321-b4c5-4fa6-b7d6-693af027f6a1.png)

**Comment by kayhantolga** [comment]
Seems weird, what it says when you put your mouse on red warning?

**Comment by LlewellynJones** [comment]
It says The type or namespace name 'Betalgo' could not be found (are you missing a using directive or an assembly reference?). Could the namespace be misspelled?

**Comment by kayhantolga** [comment]
Could you share .csproject file to please?

**Comment by LlewellynJones** [comment]
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Betalgo.OpenAI.GPT3" Version="6.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

</Project>

**Comment by LlewellynJones** [comment]
Here you go:

![Screenshot 2022-12-24 081536](https://user-images.githubusercontent.com/10248399/209443885-d22ccdd5-e5e5-4827-af7d-f0409058a4f0.png)

**Comment by kayhantolga** [comment]
Oh, I just found out what the issue is, please use 
`using OpenAI.GPT3;` instead of `using Betalgo.OpenAI.GPT3`

**Comment by kayhantolga** [comment]
Does my answer solve your problem? can I close the issue?

**Comment by LlewellynJones** [comment]
Oh, I thought I tried that. Okay, thanks!
