### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by UsamaShahid569** [betalgo/openai#416]
The [readme.file](https://github.com/betalgo/openai/blob/master/Readme.md) currently contains the following sentence:

"[This library used be to known as Betalgo.OpenAI.GPT3, now it has a new package Id Betalgo.OpenAI.](https://github.com/betalgo/openai#this-library-used-be-to-known-as-betalgoopenaigpt3-now-it-has-a-new-package-id-betalgoopenai)."

It should be :
   This library used **_to be_**
Not:
   This library used **_be to_**

**Comment by belaszalontai** [comment]
if we are editing the readme file then we should improve the description with the new features such as:

- [Chat GPT-4] (models are supported, Image analyze API not released yet by OpenAI)
- [Image DALL·E]
- [DALL·E Sample]

etc..
