### ISSUE TITLE
Question about DALL-E-3

### ISSUE THREAD

**Issue by yolo-lxf** [betalgo/openai#421]
I am using the method :
var imageResult = await openAiService.Image.CreateImage(new ImageCreateRequest
{
Prompt = "Chinese traditional dish:鱼香肉丝",
N = 1,
Size = StaticValues.ImageStatics.Size.Size1024,
ResponseFormat = StaticValues.ImageStatics.ResponseFormat.Url,
User = "TestUser",
Model=Models.Dall_e_3
});
The "Chinese traditional dish: 鱼香肉丝" in Prompt, the return of the openai interface call is the prompt word that violates the rules, but it seems that imageResult.Results does not have the specific error information returned by the api?
![image](https://github.com/betalgo/openai/assets/116715625/23755bd5-809c-4a8e-b38d-e08d5cb33ce0)

**Comment by kayhantolga** [comment]
This is the most likely response returned from the API to your request. The SDK will soon be able to handle such cases.
`<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>openresty/1.21.4.2</center> </body> </html>`
