### ISSUE TITLE
Regarding the issue of calling the Gpt_4_vision_preview model

### ISSUE THREAD

**Issue by yolo-lxf** [betalgo/openai#426]
When I use the Models.Gpt_4_vision_preview model, the responses I get are always strange. For example, when I ask "Are you a vision model?", the reply I get is "No, I am not, I am a large language model." I suspect that although I specified Models.Gpt_4_vision_preview, it is not the model that is ultimately being called.

**Comment by belaszalontai** [comment]
Have you tried this?

![image](https://github.com/betalgo/openai/assets/40541808/e16625b0-a0c1-4113-a47e-80d1b4742458)


I think Vision model is introduced for analyzing images not chat. The response is definitely coming from the requested vision model even if we don't like the answer.

**Comment by belaszalontai** [comment]
And if you provide image to this model then even the question was not related the answer looks promising :)

![image](https://github.com/betalgo/openai/assets/40541808/966a5f82-cb43-481c-8768-0d81adfa8486)

**Comment by yolo-lxf** [comment]
Yes, I have tried it, but the photos I pass through the method never correspond to the analysis results it gives. Could it be that there is an error in the way I pass the photos?
This is my code block:
![image](https://github.com/betalgo/openai/assets/116715625/1ccc3594-ed1c-4dd6-8c5b-267c139cdff5)

**Comment by belaszalontai** [comment]
Vision API haven't implemented yet @betalgo SDK. You have to wait for it..

**Comment by yolo-lxf** [comment]
Thank you so much for responding to my issue. I really appreciate your help and the work you're doing on this open-source project.

**Comment by belaszalontai** [comment]
Why your code does not work? Because in the currently implemented chat completion request handles the content property as a text (string) and you want to handle it as a json array. In the request to openAI , your content will not be a json array but a simple string contains a lot of weird characters.

**Comment by yolo-lxf** [comment]
Oh, I see. Then I'll wait for the API update.
