### ISSUE TITLE
ResponseFormat wrongfully serialized 

### ISSUE THREAD

**Issue by LucasEDT** [betalgo/openai#452]
**Describe the bug**
On AudioCreateSpeechRequest.cs line 31

![image](https://github.com/betalgo/openai/assets/93625813/bd1773d5-c07c-469e-b9a3-66062bcc96b2)

while on the api we have

![image](https://github.com/betalgo/openai/assets/93625813/de544b07-787b-4dc4-a933-661b8baf7a94)

It will silently give you an MP3 file back instead of any other type you request. Which super sucks..

Changing to this fix the issue:

![image](https://github.com/betalgo/openai/assets/93625813/2fd2d273-a2ea-4de5-994c-52ed26be34f0)

I was going to open a PR but I don't have permission :-)

Please fix it soon! thanks!

**Comment by kayhantolga** [comment]
Thank you for reporting. A fix is ready for the next version, and there are no special permission restrictions. You should be able to create a pull request (PR).
