### ISSUE TITLE
Support for RunPod vLLM serverless endpoint

### ISSUE THREAD

**Issue by carlfm01** [betalgo/openai#467]
**Is your feature request related to a problem? Please describe.**
It can be really useful to replace the enpoint with a RunPod serverless based on vLLM.

**Describe the solution you'd like**
Use url of RunPod vLLM for completion.

**Additional context**
RunPod uses "jobs" it may require management of those jobs' statuses, docs here:

https://docs.runpod.io/docs/serverless-endpoint-urls

**Comment by kayhantolga** [comment]
Hi, I don't think adding support RunPod to main library makesense, I would like to keep focus on azureAI and openAI. if you would like to add support in utilities package https://www.nuget.org/packages/Betalgo.OpenAI.Utilities/ feel free to create an PR, unforutnalty I don't have time to support it unless high demand for it.
Hi, I don't think it makes sense to add support for RunPod to the main library. I would prefer to keep the focus on AzureAI and OpenAI. However, if you would like to add support in the [utilities](https://www.nuget.org/packages/Betalgo.OpenAI.Utilities/). package, you can create a pull request. Unfortunately, I don't have time to support it unless there is high demand for it.
