### ISSUE TITLE
Make rate limit header available in ChatCompletionCreateResponse

### ISSUE THREAD

**Issue by jeancroy** [betalgo/openai#478]
**Is your feature request related to a problem? Please describe.**

For some task, OpenAI have relatively small token per minute and token per day limit.
They do keep track of the usage and give us information about it.
But that information is lost when the library de-serialize to nice objects.

https://platform.openai.com/docs/guides/rate-limits/rate-limits-in-headers

**Describe the solution you'd like**

A general solution would be a dictionary of response header.
Or even a pointer to the original HttpResponseObject

**Describe alternatives you've considered**

The alternative is to manipulate HttpClient directly. 
But then this library is not used at all.

Another alternative is to use the usage part of the response to implement our own throttling code.
But then the boundary of what is a day, what is a minute for the purpose of those limit may not be in sync. 

**Additional context**

https://platform.openai.com/docs/guides/rate-limits/rate-limits-in-headers
https://platform.openai.com/docs/guides/rate-limits/usage-tiers

**Comment by kayhantolga** [comment]
Sorry, but the rate limit should already be in [BaseResponse](https://github.com/betalgo/openai/blob/master/OpenAI.SDK/ObjectModels/ResponseModels/BaseResponse.cs). Are you looking for a field that is not present there?

**Comment by jeancroy** [comment]
OK updating from 7.3 to 7.4 fixed my issue I think.

This was newly added
`public ResponseHeaderValues? HeaderValues { get; set; }`
