### ISSUE TITLE
Questions about traversing completionResult

### ISSUE THREAD

**Issue by yolo-lxf** [betalgo/openai#532]
**Describe the bug**
![image](https://github.com/betalgo/openai/assets/116715625/fedae8a4-d4af-4793-8558-5091e6f54b78)

await foreach (var completion in completionResult) 
{
xxxx
}

When interface permissions on my openai account are disabled, the asynchronous flow does not appear to be executed and no error messages are received. How do I determine the error messages?

**Comment by kayhantolga** [comment]
This is resolved in 8.2.2 
https://github.com/betalgo/openai/pull/558
