### ISSUE TITLE
Including logprobs in request causes an error

### ISSUE THREAD

**Issue by LlewellynJones** [betalgo/openai#54]
When I include logprobs in a request I get an error:
`var builder = new ConfigurationBuilder()
    .AddJsonFile("ApiSettings.json")
    .AddUserSecrets<Program>();

IConfiguration configuration = builder.Build();
var serviceCollection = new ServiceCollection();
serviceCollection.AddScoped(_ => configuration);

serviceCollection.AddOpenAIService();
var serviceProvider = serviceCollection.BuildServiceProvider();
var sdk = serviceProvider.GetRequiredService<IOpenAIService>();

var openAiService = serviceProvider.GetRequiredService<IOpenAIService>();

var completionResult = await openAiService.Completions.CreateCompletion(new CompletionCreateRequest()
{
    Prompt = "I never go to bed after ten o'clock.",
    LogProbs = 3,
    MaxTokens = 50
}, 
Models.Davinci);`

ERROR MESSAGE:
{"The JSON value could not be converted to System.Nullable`1[System.Int32]. Path: $.choices[0].logprobs | LineNumber: 0 | BytePositionInLine: 344."}

**Comment by KosmonikOS** [comment]
I have found a bug connected with your issue and fixed it. So, wait for pull request to be accepted
