### ISSUE TITLE
gpt 4o support

### ISSUE THREAD

**Issue by abdullahbaa5** [betalgo/openai#553]
gpt 4o support

**Comment by NikolayIT** [comment]
https://github.com/betalgo/openai/pull/554

**Comment by kayhantolga** [comment]
The new models can be used by passing the strings `gpt-4o` and `gpt-4o-2024-05-13` . The master currently has a beta features(assistant); current PRs have changes from the beta version. That why we can’t release. New models will be added to the Model list with the Assistant features. Until then, please use them as strings.
