### ISSUE TITLE
Incorrect URL for Assistants api on Azure

### ISSUE THREAD

**Issue by remixtedi** [betalgo/openai#575]
**Bug Description**
According to the API specifications for Azure OpenAI assistants, the current prefix is incorrect. It should not require a deployment ID or ApiPrefix, and we should be able to call the /assistants endpoint directly. You can find the official specifications at https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-05-01-preview/inference.json

When using the Beta Assistants functionality, the API returns a 404 error. After updating the URL on my local fork, the assistants started working.

**Additional Context**
This issue is specific to the Azure provider and may not be relevant for OpenAI. and I didn't create a PR because I'm not familiar with the structure of the project and it would be simpler and safer if someone else would fix it.

**Comment by kayhantolga** [comment]
Please feel free to create a PR. I can review and make changes if necessary. I think it would be easier. 🙏

**Comment by kayhantolga** [comment]
https://github.com/betalgo/openai/pull/578 Looks good?

**Comment by remixtedi** [comment]
> #578 Looks good?

It should work! thanks <3
