### ISSUE TITLE
Missing nuget dependence on nuget version.

### ISSUE THREAD

**Issue by carlosmixz** [betalgo/openai#604]
**Describe the bug**
When you install with nuget, the functions throw a assembly missing exception, in exception.innerException.innerException.
Instaling the last version of System.ComponentModel.Annotations nuget the exception completly disappear

**Your code piece**
```

        Dim Gpt3 = New OpenAIService(New OpenAiOptions() With {
            .ApiKey = GetSetting(Application.ProductName, "Config", "APIKeyBx", "")
        })

        Dim GerarResult = Gpt3.ChatCompletion.CreateCompletion(New ChatCompletionCreateRequest() With {
            .Messages = {ChatMessage.FromUser(Prompt)},
            .Temperature = 0.7,
            .MaxTokens = 1000,
            .Model = Models.Gpt_3_5_Turbo
        })

        While Not GerarResult.IsCompleted
            EsperaMS(16)
        End While

        Try
            result = If(GerarResult.Result.Successful, GerarResult.Result.Choices(0).Message.Content, $"Erro: {If(GerarResult.Result.Error.Message, "Erro desconhecido")}")
        Catch ex As Exception
            result = "ERRO_ERRO_DESCONHECIDO_CHAT_GPT"
        End Try

```
**Result**
Result completed, but with exception and "not computed yet" state

**Expected behavior**
Expected to retuns the GPT response.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Language VB.NET
 - Version 8.5.0

**Comment by kayhantolga** [comment]
Did it start with 8.5.0? Were there such problems in previous versions?

**Comment by carlosmixz** [comment]
Nop, started before the 8.0.0.

**Comment by kayhantolga** [comment]
Please try again with the latest version and reopen this issue if the bug still exists.
