### ISSUE TITLE
ResponseFormat not present on AssistantResponse model

### ISSUE THREAD

**Issue by jmuller3** [betalgo/openai#623]
**Describe the bug**
the property for Response_Format does not exist on the AssistantResponse model
it is present in the AssistantModifyRequest, and others such as RunCreateRequest
   
 [JsonPropertyName("response_format")]
    public ResponseFormatOneOfType? ResponseFormat { get; set; }

**Expected behavior**
AssistantResponse would contain all items returned by https://api.openai.com/v1/assistants, particularly "response_format": "auto"

**Desktop (please complete the following information):**
 - OS: Windows
 - Language C#
 - Version 8.6.

**Comment by kayhantolga** [comment]
ready with 8.7.0
