### ISSUE TITLE
How to use Chunking Strategy in Vector Store?

### ISSUE THREAD

**Issue by Xavier-Mobius** [betalgo/openai#629]
Hello and thank you for this excellent SDK,

It seems to me that it is not currently possible to modify the `tools.file_search.max_num_results` parameters as defined in the documentation here: https://platform.openai.com/docs/api-reference/assistants/createAssistant#assistants-createassistant-tools
as well as the parameters `chunking.strategy.max_chunk_size_tokens` and `chunking.chunk_overlap_tokens` as defined in the documentation here: https://platform.openai.com/docs/api-reference/vector-stores-files/createFile#vector-stores-files-createfile-chunking_strategy

In practice, I'd like to be able to do something like :

```c#
await openAi.AssistantCreate(new AssistantCreateRequest
{
    Name = "...",
    Tools = new List<ToolDefinition>
    {
        new ToolDefinition
        {
            Type = "file_search",
            FileSearch = new() { MaxNumResults = 15 } // NOTE: <<< Impossible to add this parameter.
        }
    },
    // ...
}, Models.Gpt_4o, cancellationToken);
```
and
```c#
await openAi.CreateVectorStoreFile(vectorId, new CreateVectorStoreFileRequest
{
    FileId = fileId,
    ChunkingStrategy = new() // NOTE: <<< Impossible to add this parameter.
    {
        Type = "static",
        Static = new ()
        {
            MaxChunkSizeTokens = 400,
            ChunkOverlapTokens = 100
        }
    }
}, cancellationToken);
```

Is this feature not implemented (and if so, are there any plans to do so soon?) or am I missing something?

In any case, thanks for all the work you've already achieved in this excellent repository 😃

**Comment by kayhantolga** [comment]
Hi, thanks for submitting the issue. I'm planning an update this week. If you know any other missing parameters, please report them as well.

**Comment by Xavier-Mobius** [comment]
Amazing! I didn't think the correction would come so quickly, thank you very much. :smile: 

The changes in my first post are all I need, but, for completeness, I noticed that :

- There's also a parameter: `tools.file_search.ranking_options` in the same place as `max_num_results`

- In addition to being configurable from the “_Vector Store File_” creation request, as mentioned above, is also configurable from :
   - The request to create a “_Vector Store File Batch_” (https://platform.openai.com/docs/api-reference/vector-stores-file-batches/createBatch#vector-stores-file-batches-createbatch-chunking_strategy)
   - The request to create a “_Vector Store_” (https://platform.openai.com/docs/api-reference/vector-stores/create#vector-stores-create-chunking_strategy)
- And it visible on return in the the "_Vector Store File object_” (https://platform.openai.com/docs/api-reference/vector-stores-files/file-object#vector-stores-files/file-object-chunking_strategy).

I hope this helps. Thanks again :smile:
