### ISSUE TITLE
Change the DLL / Namespace name

### ISSUE THREAD

**Issue by roldengarm** [betalgo/openai#640]
**Is your feature request related to a problem? Please describe.**
We're using both this library as well as Semantic Kernel. In a recent version, they added a dependency on the OpenAI package.
This is causing a conflict, as both Betalgo.OpenAI and the OpenAI packages use OpenAI as namespace and DLL name. See [this issue](https://github.com/microsoft/semantic-kernel/issues/8994#issuecomment-2379863649) for more info

**Describe the solution you'd like**
- Rename OpenAI.dll to Betalgo.OpenAI.dll
- Change the namespace from OpenAI to Betalgo.OpenAI

**Describe alternatives you've considered**
I'm not aware of any alternatives that will work. I tried a package alias, but that still did not solve the problem, as per https://github.com/microsoft/semantic-kernel/issues/8994#issuecomment-2377833396

**Comment by kayhantolga** [comment]
Thanks for reporting this. Since it will be a breaking change, I need some time to carefully consider it.

**Comment by chibounisme** [comment]
Had the same exact issue, but this time using the official OpenAI .NET [library](https://github.com/openai/openai-dotnet).

**Comment by kayhantolga** [comment]
🔨 Decision made: The namespace will be updated after the release of the Realtime API integration.

**Comment by kayhantolga** [comment]
Thank you for reporting.

`Betalgo.Ranul.OpenAI` is the new `PackageId` and namespace.

Please check the wiki for the migration guide: [https://github.com/betalgo/openai/wiki/Migration-Guides-(mostly-for-breaking-changes)](https://github.com/betalgo/openai/wiki/Migration-Guides-(mostly-for-breaking-changes))
