### ISSUE TITLE
Realtime WebSocket

### ISSUE THREAD

**Issue by sithwillrule** [betalgo/openai#641]
OpenAI revealed a new realtime model accessible via API

if no one is adding this feature I would be happy to implement it!

More details:
https://platform.openai.com/docs/guides/realtime

**Comment by kayhantolga** [comment]
Hi, Thanks for the support! I have already started to work on this.

**Comment by kayhantolga** [comment]
https://github.com/betalgo/openai/pull/667 PR is ready, if anyone would like to review

**Comment by kayhantolga** [comment]
v8.9.0
