### ISSUE TITLE
Realtime API 

### ISSUE THREAD

**Issue by MayDay-wpf** [betalgo/openai#647]
Although some users have already mentioned this update, I'm still so excited that I want to share it again—I'd like to offer a simple cup of coffee ☕ as a token of gratitude.

**Comment by kayhantolga** [comment]
Thanks for the kind support! It really keeps me motivated. Good news, I’ve already started working on it!

**Comment by danielekbom** [comment]
This will be awesome, thank you!
Do you have any time estimations for when its ready?

**Comment by kayhantolga** [comment]
https://github.com/betalgo/openai/pull/667 PR is ready, if anyone would like to review

**Comment by kayhantolga** [comment]
v8.9.0
