### ISSUE TITLE
Is it possible to upload file in the chat completion?

### ISSUE THREAD

**Issue by markostojkov** [betalgo/openai#656]
Use case:
Upload PDF to OpenAi and let GPT4o return information.

I can easily do this in the assistant on their playground

Now I couldn't find anything about this in your docs
![image](https://github.com/user-attachments/assets/0f8f0f48-c4b5-4c1f-9800-4a8c7078c813)
Here is how I upload the file and next I want to call the Chat API and pass the FILE id as a resource.

Is that possible with this SDK?

Thank you

**Comment by markostojkov** [comment]
I found how to do it

**Comment by LucaZiegler** [comment]
> I found how to do it

And how??
