### ISSUE TITLE
OpenAI.ObjectModels.SharedModels.AssistantResponse missing temperature, top_p

### ISSUE THREAD

**Issue by jmuller3** [betalgo/openai#657]
**Describe the bug**
temperature and top_p props are not present in result model from AssistantRetrieve

**Your code piece**
- code flow attempts to spawn a clone of an existing assistant for modifications, but needed props are not available from the AssistantResponse 
`AssistantResponse existing = await _service(serviceParams).AssistantRetrieve(assistantID);
AssistantResponse response = await _service(serviceParams).AssistantCreate(new AssistantCreateRequest()
{
    Description = $"cloned from: {existing.Id} at " + DateTime.UtcNow.ToString("g"),
    Instructions = existing.Instructions,
    Model = existing.Model,
    Name = "Cloned - " + existing.Name,
    ToolResources=existing.ToolResources,
    Metadata = new Dictionary<string, string>() { { "Parent", existing.Id }}_,
    Temperature= **existing.Temperature**,
    TopP = **existing.TopP**_
});
return response;`

**Result**
 no result currently, can't pass along the props because I can't access them

**Expected behavior**
AssistantResponse supports all props available in AssistantCreate/Modify

**Screenshots**
n/a

**Desktop (please complete the following information):**
Windows, C#, 8.7.2

**Additional context**
N/A

**Comment by kayhantolga** [comment]
https://github.com/betalgo/openai/releases/tag/v8.10.0
