### ISSUE TITLE
Add `store` boolean option for ChatCompletionCreateRequest

### ISSUE THREAD

**Issue by connellPortrait** [betalgo/openai#660]
Hello, are there any considerations to make adding the `store` boolean param to the `ChatCompletionCreateRequest` ?
https://platform.openai.com/docs/api-reference/chat/create?lang=python

**Comment by kayhantolga** [comment]
https://github.com/betalgo/openai/releases/tag/v8.10.0

**Comment by connellPortrait** [comment]
Thanks!
