### ISSUE TITLE
Method not found: '!!0 Microsoft.Extensions.AI.IChatClient.GetService(System.Object)'

### ISSUE THREAD

**Issue by jcmag** [betalgo/openai#685]
Hi,

I want to use the Microsoft.Extensions.AI.IChatClient interface in my code (to be able to call ChatGPT, Anthropic, Mistral etc.).
The problem is that as soon as I add this line of code:

client = new OpenAIService(new OpenAIOptions { ApiKey = key });

I get this error at runtime :

System.MissingMethodException: Method not found: '!!0 Microsoft.Extensions.AI.IChatClient.GetService(System.Object)'.

Any idea why?

Betalgo.Ranul.OpenAI v9.0.0
.NET 9.0

**Comment by kayhantolga** [comment]
Thanks for reporting. Let me check. If you can share a sample project, it would help a lot.

**Comment by jcmag** [comment]
Hi,

Here is a sample project that reproduces the exception.
[Bug.zip](https://github.com/user-attachments/files/17997715/Bug.zip)

Actually, the error only occurs when I reference the other packages (Anthropic.SDK and Mistral.SDK), so it might be a conflict between the three packages. I have also contacted the owners of the other packages, as the issue may not be with your package.

**Comment by jcmag** [comment]
from the Mistral.SDK author:

"I noted when I removed Betalgo.Ranul.OpenAI, the app seems to run fine. This does appear to be some sort of version conflict and I note that there are some dependency mismatches between my libraries and theirs, but not related to IChatClient...it just has a LOT of dependencies so it's a little tough to tell where exactly the conflict is coming from"

**Comment by kayhantolga** [comment]
I think this is because Microsoft.Extensions.AI.Abstractions is still in preview, and we are using a different version of the preview model. I may need to update it to the latest version and fix the missing implementation.

**Comment by kayhantolga** [comment]
resolved
https://github.com/betalgo/openai/releases/tag/v9.0.1
