### ISSUE TITLE
Fine Tuning Model/Engine error

### ISSUE THREAD

**Issue by kayhantolga** [betalgo/openai#75]
Currently, we have an issue with model(engine) usage. It is preventing to use Fine Tuned Models.

I am planning to fix this next week (16-22 January). Please follow this issue for notifications.

**Comment by kayhantolga** [comment]
solved in v6.6.5

**Comment by mattd1980** [comment]
is it possible that the issue is back in 6.8.1, right now :

```
 var completionResult = await openAiService.ChatCompletion.CreateCompletion(new ChatCompletionCreateRequest
                    {
                        Messages = messages,
                        Model = "ada:ft-personal-2023-03-26-22-39-52"
                    });

```                    
Gives me a : Invalid URL (POST /v1/chat/completions)

**Comment by kayhantolga** [comment]
I don't think you can use `chat endpoint` with Finetuned models 🤔 If not please let me know. Did your postman request return 200? Could you share a sample request and response, please?
