### ISSUE TITLE
JSON value could not be converted to System.Boolean

### ISSUE THREAD

**Issue by Daimerias** [betalgo/openai#9]
I got following error when i try call await EngineTestHelper.FetchEnginesTest(sdk); method.

I have tested some other methods and they seemed to work but this one is not. I do not know what is the issue.

**Comment by kayhantolga** [comment]
I found a difference between documentation and OpenAI response.
Documentation doesn't mention `ready` is nullable, I released a fix for it. You can fetch the latest version or update your NuGet package to version 6.0.0. 

I hope this will solve your issue. Thanks for reporting.

 #10  OpenAI.SDK/Models/ResponseModels/EngineResponseModels/EngineRetrieveResponse.cs

**Documentation**:
![image](https://user-images.githubusercontent.com/1096362/158028123-a5505ea4-e54b-4bee-9730-4c3385859f25.png)
**Actual Response**:
![image](https://user-images.githubusercontent.com/1096362/158028150-fd7a8f99-6fcd-4345-bde7-844f0b1963c5.png)
