### ISSUE TITLE
CancellationToken support

### ISSUE THREAD

**Issue by robertlyson** [betalgo/openai#90]
Hi 👋 

**Is your feature request related to a problem? Please describe.**
I would like to be able to pass CancellationToken to `IOpenAIService` endpoints. 

**Describe the solution you'd like**
For example when calling completions endpoint would be great to pass token like this
```
var result = await _service.Completions.CreateCompletion(new CompletionCreateRequest    
    {
        ..                                                                                   
    },                                                                                  
    cancellationToken: cancellationToken);                                              
```

**Describe alternatives you've considered**

x

**Additional context**

x

Maybe I'm coming with this after someone already was thinking of this and you have thoughts / opinions already? Happy to prepare PR for this.

Thanks!

**Comment by kayhantolga** [comment]
Great one! We definitely need this. I think we can add cancellationToken to most of the functions. I am thinking of syntax like this, what do you think?
`functionX(arg1, arg 2, CancellationToken cancellationToken = default)`
